# Generated by Django 4.0.5 on 2022-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alaki',
            field=models.CharField(default='salam', max_length=50),
            preserve_default=False,
        ),
    ]
