# Generated by Django 4.0.5 on 2022-09-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_alaki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alaki',
        ),
    ]
