# Generated by Django 4.0.5 on 2022-08-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detailed_text', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('age_author', models.DecimalField(decimal_places=1, max_digits=3)),
                ('date_written', models.DateTimeField()),
            ],
        ),
    ]
